//{ 1: "Ünlü İsimler" },
//{ 2: "Coğrafya"},
//{ 3: "Edebiyat"},
//{ 4: "Genel Kültür" },
//{ 5: "Yabancı Dizi & Filmler"},
//{ 6: "Karışık" },
//{ 7: "Müzik" },
//{ 8: "Türk Dizi & Filmler" },
//{ 9: "Tarih" },

const Word = [
  {
    spokenWord: "Güvercin",
    forbiddenWords: ["Kanat", "Hayvan", "Taklacı", "Yem", "Kuş"],
    category: ["6"],
  },
  {
    spokenWord: "Van Gogh",
    forbiddenWords: ["Tablo", "Yıldızlı Gece", "Resim", "Kulak", "Ressam"],
    category: [" 9", "1", "6", "4"],
  },
  {
    spokenWord: "Müzik",
    forbiddenWords: ["Nota", "Çalmak", "Konser", "Şarkı", "Dinlemek"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Tarihi Eser",
    forbiddenWords: ["Antika", "Koleksiyon", "Müze", "Gezi", "Turizm"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Basketbol",
    forbiddenWords: ["Hidayet Türkoğlu", "Saha", "Pota", "Futbol", "Smaç"],
    category: ["6"],
  },
  {
    spokenWord: "Barış Manço",
    forbiddenWords: [
      "Şarkıcı",
      "Müzisyen",
      "Arkadaşım Eşşek",
      "Dönence",
      "Gamzedeyim",
    ],
    category: ["7", "1", "6"],
  },
  {
    spokenWord: "Karbonhidrat",
    forbiddenWords: ["Besin", "Glukoz", "Enerji", "Yağ", "Protein"],
    category: ["6"],
  },
  {
    spokenWord: "Kış Sporları",
    forbiddenWords: ["Kayak", "Snowboard", "Patenci", "Dağ", "Kamp"],
    category: ["6", "4"],
  },
  {
    spokenWord: "Nasa",
    forbiddenWords: ["Uzay", "Astronot", "Apollo", "Mars", "Iss"],
    category: ["6", "4"],
  },
  {
    spokenWord: "Alpler",
    forbiddenWords: ["Dağ", "Manzara", "Ski", "Fransa", "İsviçre"],
    category: ["6", "2", "4"],
  },
  ,
  {
    spokenWord: "Çikolata",
    forbiddenWords: ["Tatlı", "Kakao", "Şeker", "Bitter", "Sütlü"],
    category: ["6"],
  },
  {
    spokenWord: "Çay",
    forbiddenWords: ["İçecek", "Demleme", "Bardak", "Kahvaltı", "Sıcak"],
    category: ["6"],
  },
  {
    spokenWord: "Kebap",
    forbiddenWords: ["Yemek", "Mangal", "Et", "İskender", "Adana"],
    category: ["6"],
  },
  {
    spokenWord: "Her Şey Çok Güzel Olacak",
    forbiddenWords: [
      "Cem Yılmaz",
      "Mazhar Alanson",
      "Bar",
      "Film",
      "Ekrem İmamoğlu",
    ],
    category: ["8 ", "6", "4"],
  },
  {
    spokenWord: "İstanbul",
    forbiddenWords: ["Şehir", "Boğaziçi", "Kıtalar", "Ayasofya", "Kız Kulesi"],
    category: ["6", "2"],
  },
  {
    spokenWord: "Atatürk",
    forbiddenWords: [
      "Mustafa Kemal",
      "Türkiye",
      "Kurtuluş Savaşı",
      "Nutuk",
      "Anıtkabir",
    ],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Efes",
    forbiddenWords: ["Antik", "İzmir", "Tarih", "Tuborg", "Bira"],
    category: [" 9", "6", "4"],
  },
  {
    spokenWord: "Nâzım Hikmet",
    forbiddenWords: [
      "Şair",
      "Yazar",
      "Komünist",
      "Benimle Kal",
      "Mavi Gözlü Dev",
    ],
    category: ["3", , "6"],
  },
  {
    spokenWord: "Kırmızı",
    forbiddenWords: ["Renk", "Bayrak", "Gül", "Nar", "Fenerbahçe"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Buzdolabı",
    forbiddenWords: ["Beyaz Eşya", "Soğutma", "Yiyecek", "Ev", "Elektrik"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Buzdolabı",
    forbiddenWords: ["Beyaz Eşya", "Soğutma", "Yiyecek", "Ev", "Elektrik"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Oksijen",
    forbiddenWords: ["Solunum", "Gaz", "Nefes", "Hidrojen", "Hava"],
    category: ["6"],
  },
  {
    spokenWord: "Zalim",
    forbiddenWords: ["Yalın", "Oyunbozan", "Bitanem", "Hakkın", "Algida"],
    category: ["4", "6", "7"],
  },
  {
    spokenWord: "İlber Ortaylı",
    forbiddenWords: [
      "Tarih",
      "Celal Şengör",
      "Fatih Altaylı",
      "Profesör",
      "Üniversite",
    ],
    category: ["4", "6", "1"],
  },
  {
    spokenWord: "İnception",
    forbiddenWords: [
      "Rüya",
      "Leonardo Dicaprio",
      "Bilinç",
      "Christopher Nolan",
      "Interstaller",
    ],
    category: ["4", "6", "5"],
  },
  {
    spokenWord: "Godfather",
    forbiddenWords: ["Al Pacıno", "Marlon Brando", "Mafya", "Sicilya", "Aile"],
    category: ["4", "6", "5"],
  },
  {
    spokenWord: "Mimar Sinan",
    forbiddenWords: [
      "Osmanlı",
      "Camii",
      "Süleymaniye",
      "Tarihi Eser",
      "Mühendis",
    ],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Uzaylılar",
    forbiddenWords: ["Uzay", "Yaratık", "Galaksi", "Roswell", "Bilinmeyen"],
    category: ["6"],
  },
  {
    spokenWord: "Sürrealizm",
    forbiddenWords: ["Realizm", "Dali", "Freud", "Rüya", "Gerçeküstü"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Hamlet",
    forbiddenWords: ["Shakespeare", "Tiyatro", "Oyun", "Drama", "Kral"],
    category: ["3", "6"],
  },
  {
    spokenWord: "Elon Musk",
    forbiddenWords: ["Tesla", "Spacex", "Mars", "Dogecoin", "Girişimci"],
    category: ["1", "6"],
  },
  {
    spokenWord: "Kahve",
    forbiddenWords: ["İçecek", "Filtre", "Espresso", "Latte", "Bardak"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Kraliyet Ailesi",
    forbiddenWords: ["İngiltere", "Kraliçe", "Prens", "Elızabeth", "Taç"],
    category: [" 9", "4", "6"],
  },
  {
    spokenWord: "Futbol",
    forbiddenWords: ["Top", "Kale", "Oyuncu", "Saha", "Antrenör"],
    category: ["6"],
  },
  {
    spokenWord: "Gastronomi",
    forbiddenWords: ["Lezzet", "Yemek", "Mutfak", "Tat", "Şef"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Fransızca",
    forbiddenWords: ["Dil", "Fransa", "Aksan", "Kurs", "Cümle"],
    category: ["4", "6"],
  },
  {
    spokenWord: "İç Denetçi",
    forbiddenWords: ["Denetim", "Kurum", "İşletme", "Risk", "Kontrol"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Kadıköy",
    forbiddenWords: ["İstanbul", "İlçe", "Moda", "Sahil", "Bağdat"],
    category: ["6", "2"],
  },
  {
    spokenWord: "Müze",
    forbiddenWords: ["Topkapı", "Tarih", "Eser", "Sergi", "Turizm"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Almanya",
    forbiddenWords: ["Ülke", "Berlin", "Münih", "Avrupa", "Hitler"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Simit",
    forbiddenWords: ["Poğaça", "Kahvaltı", "Sokak", "Susam", "Ekmek"],
    category: ["6"],
  },
  {
    spokenWord: "Dedektif",
    forbiddenWords: ["Polis", "Cinayet", "Suç", "Sherlock Holmes", "Roman"],
    category: ["3", "6"],
  },
  {
    spokenWord: "Hip Hop",
    forbiddenWords: ["Müzik", "Rap", "Breakdance", "Ceza", "Mc"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Yoga",
    forbiddenWords: ["Nefes", "Meditasyon", "Om", "Plates", "Zihin"],
    category: ["6"],
  },
  {
    spokenWord: "Antik Mısır",
    forbiddenWords: ["Piramit", "Hiyeroglif", "Firavun", "Sfenks", "Eski"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Yapay Zeka",
    forbiddenWords: ["Bilgisayar", "Programlama", "Veri", "Robot", "Chatgpt"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Güneş",
    forbiddenWords: ["Yıldız", "Enerji", "Işık", "Gündüz", "Ay"],
    category: ["6", "2"],
  },
  {
    spokenWord: "Güneydoğu Anadolu",
    forbiddenWords: ["Turizm", "Kültür", "İklim", "Bölge", "Sınır"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Şato",
    forbiddenWords: ["Kale", "Fransa", "Saray", "Avrupa", "Tarihi Eser"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Denizaltı",
    forbiddenWords: ["Su", "Gemi", "Askeri", "Batık", "Dalış"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Gastrit",
    forbiddenWords: ["Mide", "Ağrı", "Hazım", "Gaz", "Beslenme"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Arkeoloji",
    forbiddenWords: ["Tarih", "Kazı", "Eser", "Kültür", "Antik"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Bilim Kurgu",
    forbiddenWords: ["Roman", "Film", "Uzay", "Robot", "Gelecek"],
    category: [, "5", "8 ", "6"],
  },
  {
    spokenWord: "Bale",
    forbiddenWords: ["Dans", "Tiyatro", "Kuğu Gölü", "Müzik", "Kostüm"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Ankara",
    forbiddenWords: ["Başkent", "Türkiye", "Atatürk", "İl", "Şehir"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Turp",
    forbiddenWords: ["Sebze", "Baharat", "Kış", "Salata", "Lahana"],
    category: ["6"],
  },
  {
    spokenWord: "Strateji",
    forbiddenWords: ["Plan", "Oyun", "Karar", "Liderlik", "Savaş"],
    category: ["6"],
  },
  {
    spokenWord: "Yüzme",
    forbiddenWords: ["Havuz", "Deniz", "Kulaç", "Rekabet", "Olimpiyat"],
    category: ["6"],
  },
  {
    spokenWord: "Deney",
    forbiddenWords: ["Keşif", "Tepkime", "Araştırma", "Laboratuvar", "Kimya"],
    category: ["6"],
  },
  {
    spokenWord: "Tiyatro",
    forbiddenWords: ["Sahne", "Oyuncu", "Perde", "Drama", "Skeç"],
    category: [, "6"],
  },
  {
    spokenWord: "El Yazısı",
    forbiddenWords: ["Kalem", "Mektup", "Kağıt", "Not", "Okuma"],
    category: ["6"],
  },
  {
    spokenWord: "Ayvalık",
    forbiddenWords: ["Ege", "Balık", "Cunda", "Sahil", "Zeytin"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Trafik",
    forbiddenWords: ["Araç", "Sürücü", "Kurallar", "Kaza", "Yol"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Gaziantep",
    forbiddenWords: ["Şehir", "Baklava", "Kebap", "Tatlı", "Zeugma"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Pirinç",
    forbiddenWords: ["Bulgur", "Yemek", "Pilav", "Tarım", "Tavuk"],
    category: ["6"],
  },
  {
    spokenWord: "Mimar Sinan",
    forbiddenWords: ["Türkiye", "Osmanlı", "Camii", "Selimiye", "Eser"],
    category: [" 9", "6"],
  },
  {
    spokenWord: "Kıbrıs",
    forbiddenWords: ["Ada", "Akdeniz", "Yavru Vatan", "Türk", "Barış"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Muhallebi",
    forbiddenWords: ["Sütlü", "Tatlı", "Puding", "Dondurma", "Saray"],
    category: ["6"],
  },
  {
    spokenWord: "Diksiyon",
    forbiddenWords: ["Konuşma", "Telaffuz", "Ses", "Sunucu", "Etkili"],
    category: ["6"],
  },
  {
    spokenWord: "Çizgi Roman",
    forbiddenWords: ["Görsel", "Karakter", "Çizim", "Manga", "Süper Kahraman"],
    category: ["6"],
  },
  {
    spokenWord: "Sömestr",
    forbiddenWords: ["Okul", "Ders", "Tatil", "Eğitim", "Sınav"],
    category: ["6"],
  },
  {
    spokenWord: "Simit Sarayı",
    forbiddenWords: ["Poğaça", "Susam", "Cafe", "Kahvaltı", "Tuzlu"],
    category: ["6"],
  },
  {
    spokenWord: "İpek",
    forbiddenWords: ["Kumaş", "Böcek", "Dokuma", "Yün", "Bursa"],
    category: ["6"],
  },
  {
    spokenWord: "Küba",
    forbiddenWords: ["Adası", "Karayipler", "Havana", "Sosyalizm", "Amerika"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Bisiklet",
    forbiddenWords: ["Pedal", "Tekerlek", "Dağ", "Yol", "Trafik"],
    category: ["6"],
  },
  {
    spokenWord: "Harita",
    forbiddenWords: ["Yol", "Coğrafya", "Şehir", "Ülke", "Uydu"],
    category: ["4", "2", "6"],
  },
  {
    spokenWord: "Akdeniz",
    forbiddenWords: ["Deniz", "Yaz", "Mavi", "Turizm", "Kıyı"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Kalem",
    forbiddenWords: ["Mürekkep", "Yazmak", "Ofis", "Defter", "Kırtasiye"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Pythagoras",
    forbiddenWords: ["Üçgen", "Matematik", "Hipothenuse", "Teorem", "Geometri"],
    category: ["3", "1", "6"],
  },
  {
    spokenWord: "Piyano",
    forbiddenWords: ["Tuşlar", "Müzik", "Çalgı", "Klasik", "Orkestra"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Gözlük",
    forbiddenWords: ["Lens", "Görme", "Göz", "Aksesuar", "Göz Doktoru"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Antarktika",
    forbiddenWords: ["Buzullar", "Kutup", "Pinguin", "Soğuk", "Kıta"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Leonardo Da Vinci",
    forbiddenWords: ["Rönesans", "Tablo", "Sanatçı", "Mona Lisa", "İcat"],
    category: ["1", "3", "6"],
  },
  {
    spokenWord: "Gitar",
    forbiddenWords: ["Teller", "Akustik", "Elektro", "Çalmak", "Enstrüman"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Amazon Ormanı",
    forbiddenWords: [
      "Yağmur Ormanı",
      "Brezilya",
      "Ekosistem",
      "Nehir",
      "Bitki",
    ],
    category: ["2", "4", "6"],
  },

  {
    spokenWord: "Gökyüzü",
    forbiddenWords: ["Bulut", "Uçak", "Mavi", "Gündüz", "Yıldız"],
    category: ["4", "6"],
  },
  {
    spokenWord: "William Shakespeare",
    forbiddenWords: ["Oyun", "Tragedya", "Yazar", "Romeo", "Juliet"],
    category: ["3", "1", "6"],
  },
  {
    spokenWord: "Futbol",
    forbiddenWords: ["Top", "Kale", "Stadyum", "Maç", "Tribün"],
    category: ["6", "9"],
  },
  {
    spokenWord: "Mozaik",
    forbiddenWords: ["Parça", "Sanat", "Desen", "Seramik", "Duvar"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Teleskop",
    forbiddenWords: ["Uzay", "Gözlem", "Yıldız", "Araştırma", "Gök Cisimleri"],
    category: ["4", "6"],
  },
  {
    spokenWord: "İstanbul",
    forbiddenWords: ["Boğaz", "Şehir", "Tarihi", "Minare", "Ayasofya"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Albert Einstein",
    forbiddenWords: ["Fizik", "Teori", "Dâhî", "Işık", "Bilim"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Balina",
    forbiddenWords: ["Deniz", "Büyük", "Memeli", "Su", "Leviathan"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Pusula",
    forbiddenWords: ["Yön", "Kuzey", "Manyetik", "Denizcilik", "Gösterge"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Mona Lisa",
    forbiddenWords: [
      "Tablo",
      "Gülümseme",
      "Sanat",
      "Leonardo Da Vinci",
      "Kadın",
    ],
    category: ["4", "6"],
  },
  {
    spokenWord: "Keman",
    forbiddenWords: ["Telli", "Klasik", "Çalgı", "Yay", "Orkestra"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Eiffel Kulesi",
    forbiddenWords: ["Demir", "Paris", "Manzara", "Fransa", "Yüksek"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Picasso",
    forbiddenWords: ["Tablo", "Sanatçı", "Kubizm", "Boya", "Guernica"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Astronomi",
    forbiddenWords: ["Gök Cisimleri", "Uzay", "Gözlem", "Yıldız", "Evren"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Lale",
    forbiddenWords: ["Çiçek", "Bahar", "Hollanda", "Soğan", "Renk"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Sünger Bob",
    forbiddenWords: [
      "Kare Pantolon",
      "Denizaltı",
      "Çizgi Film",
      "Patrıck",
      "Animasyon",
    ],
    category: ["5", "6"],
  },
  {
    spokenWord: "Mona Lisa",
    forbiddenWords: [
      "Tablo",
      "Gülümseme",
      "Sanat",
      "Leonardo Da Vinci",
      "Kadın",
    ],
    category: ["1", "3", "6"],
  },
  {
    spokenWord: "Keman",
    forbiddenWords: ["Telli", "Klasik", "Çalgı", "Yay", "Orkestra"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Eiffel Kulesi",
    forbiddenWords: ["Demir", "Paris", "Manzara", "Fransa", "Yüksek"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Picasso",
    forbiddenWords: ["Tablo", "Sanatçı", "Kubizm", "Boya", "Guernica"],
    category: ["1", "3", "6"],
  },
  {
    spokenWord: "Astronomi",
    forbiddenWords: ["Gök Cisimleri", "Uzay", "Gözlem", "Yıldız", "Evren"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Lale",
    forbiddenWords: ["Çiçek", "Bahar", "Hollanda", "Soğan", "Renk"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Maraton",
    forbiddenWords: ["Koşu", "Yarış", "Bitiş Çizgisi", "Spor", "Dayanıklılık"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Rönesans",
    forbiddenWords: [
      "Sanat",
      "Michelangelo",
      "Da Vinci",
      "Dönem",
      "Yeniden Doğuş",
    ],
    category: ["3", "2", "6"],
  },
  {
    spokenWord: "Balerin",
    forbiddenWords: ["Dans", "Pirouette", "Bale", "Kostüm", "Sahne"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Güneş",
    forbiddenWords: ["Yıldız", "Işık", "Gök Cisimleri", "Sıcak", "Gün"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Opera",
    forbiddenWords: ["Sahne", "Müzik", "Ses", "Perde", "Şan"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Amazon Nehri",
    forbiddenWords: ["Orman", "Güney Amerika", "Akarsu", "Tropikal", "Kano"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Pasta",
    forbiddenWords: ["Tatlı", "Hamur", "Krem", "Pastane", "Çikolata"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Yıldızlar",
    forbiddenWords: ["Gökyüzü", "Uzay", "Parlak", "Galaksi", "Gece"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Köprü",
    forbiddenWords: ["Bağlantı", "Nehir", "Ulaşım", "Yol", "Mimar"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Drama",
    forbiddenWords: ["Tiyatro", "Oyun", "Sanat", "Roller", "Perde"],
    category: ["3", "6"],
  },
  {
    spokenWord: "Kelebek",
    forbiddenWords: ["Kanat", "Renkli", "Sinek", "Hava", "Lepidoptera"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Pasta",
    forbiddenWords: ["Tatlı", "Hamur", "Krem", "Pastane", "Çikolata"],
    category: ["4", "6"],
  },
  {
    spokenWord: "Yıldızlar",
    forbiddenWords: ["Gökyüzü", "Uzay", "Parlak", "Galaksi", "Gece"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Köprü",
    forbiddenWords: ["Bağlantı", "Nehir", "Ulaşım", "Yol", "Mimar"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Drama",
    forbiddenWords: ["Tiyatro", "Oyun", "Sanat", "Roller", "Perde"],
    category: ["3", "6"],
  },
  {
    spokenWord: "Kelebek",
    forbiddenWords: ["Kanat", "Renkli", "Sinek", "Hava", "Lepidoptera"],
    category: ["2", "4", "6"],
  },
  {
    spokenWord: "Celal Şengör",
    forbiddenWords: [
      "İlber Ortaylı",
      "Jeoloji",
      "Profesör",
      "Bilim İnsanı",
      "Akademisyen",
    ],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Ahmet Davutoğlu",
    forbiddenWords: ["Gelecek Partisi", "Siyaset", "Hoca", "Deva", "Başbakan"],
    category: ["1", "6"],
  },
  {
    spokenWord: "Tarkan",
    forbiddenWords: ["Karma", "Dudu", "Pop", "Kuzu Kuzu", "Geççek"],
    category: ["1", "7", "6"],
  },
  {
    spokenWord: "Osman Hamdi Bey",
    forbiddenWords: [
      "Ressam",
      "Müze",
      "Kaplumbağa Terbiyecisi",
      "İki Müzisyen Kız",
      "Sanat",
    ],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Bedri Rahmi Eyüboğlu",
    forbiddenWords: [
      "Yaradana Mektuplar",
      "Ressam",
      "Yazar",
      "Karadut",
      "Canım Anadolu",
    ],
    category: ["1", "3", "4", "6"],
  },
  {
    spokenWord: "Süleyman Demirel",
    forbiddenWords: [
      "Siyaset",
      "Şapka",
      "Isparta",
      "Cumhurbaşkanı",
      "Binaenaleyh",
    ],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Bülent Ecevit",
    forbiddenWords: [
      "Kara Oğlan",
      "Koalisyon",
      "Başbakan",
      "Siyaset",
      "Rahşan",
    ],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Pablo Picasso",
    forbiddenWords: ["Ressam", "Kübist", "Guernica", "İspanyol", "Sanat"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Frida Kahlo",
    forbiddenWords: ["Ressam", "Meksikalı", "Portre", "Diego Rivera", "Ağrı"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Steve Jobs",
    forbiddenWords: ["Apple", "Iphone", "Teknoloji", "Mac", "İpad"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Albert Eınsteın",
    forbiddenWords: ["Fizikçi", "Görelilik", "Bilim", "Nobel", "Alman"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Michael Jackson",
    forbiddenWords: [
      "Pop",
      "Beat It",
      "Moonwalk",
      "Smooth Criminal",
      "Billie Jean",
    ],
    category: ["1", "4", "7", "6"],
  },
  {
    spokenWord: "Beyonce",
    forbiddenWords: ["Şarkıcı", "Amerikalı", "Müzik", "Pop", "Rihanna"],
    category: ["1", "7", "6"],
  },
  {
    spokenWord: "Salvador Dali",
    forbiddenWords: ["Ressam", "İspanyol", "Sürrealist", "Saat", "Bıyık"],
    category: ["1", "4", "6"],
  },
  {
    spokenWord: "Tolstoy",
    forbiddenWords: [
      "Savaş Ve Barış",
      "Rus",
      "Yazar",
      "Anna Karenina",
      "Roman",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Yahya Kemal Beyatlı",
    forbiddenWords: [
      "Şair",
      "Sessiz Gemi",
      "Akıncılar",
      "Bir Başka Tepeden",
      "Kar Musikileri",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Sabahattin Ali",
    forbiddenWords: [
      "Kürk Mantolu Madonna",
      "Kuyucaklı Yusuf",
      "Sırça Köşk",
      "Yazar",
      "Geçmiyor Günler",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Ahmet Haşim",
    forbiddenWords: [
      "Şair",
      "Piyale",
      "Merdiven",
      "Fecri Ati",
      "Bir Yaz Gecesi Hatırası",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Cemal Süreya",
    forbiddenWords: [
      "Şair",
      "Üvercinka",
      "Sizin Hiç Babanız Öldü Mü?",
      "Sevda Sözleri",
      "İkinci Yeni",
    ],
    category: ["1", "3", "6", "4"],
  },

  {
    spokenWord: "Atilla İlhan",
    forbiddenWords: [
      "Şair",
      "Ben Sana Mecburum",
      "Ayrılık Sevdaya Dahil",
      "Üçüncü Şahsın Şiiri",
      "Aysel Git Başımdan",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Necip Fazıl Kısakürek",
    forbiddenWords: [
      "Şair",
      "Kaldırımlar",
      "Sakarya Türküsü",
      "Çile",
      "Zindandan Mehmede Mektup",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Halide Edip Adıvar",
    forbiddenWords: [
      "Ateşten Gömlek",
      "Türkün Ateşle İmtihanı",
      "Sinekli Bakkal",
      "Kadın",
      "Yazar",
    ],
    category: ["1", "3", "6", "4"],
  },
  {
    spokenWord: "Pulp Fıctıon",
    forbiddenWords: [
      "Kıll Bıll",
      "Quentin Tarantino",
      "Uma Thurman",
      "John Travolta",
      "Samuel L. Jackson",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Kıll Bıll",
    forbiddenWords: [
      "Pulp Fıctıon",
      "Quentin Tarantino",
      "Uma Thurman",
      "Kılıç",
      "Islık",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Tıtanıc",
    forbiddenWords: [
      "Iceberg",
      "Batmak",
      "Leonardo Dıcaprıo",
      "Kate Wınslet",
      "Gemi",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Taxı Drıver",
    forbiddenWords: [
      "Robert De Niro",
      "Martın Scorsese",
      "New York",
      "Saç",
      "Jodı Foster",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Shutter Island",
    forbiddenWords: [
      "Leonardo Dıcaprıo",
      "Martın Scorsese",
      "Deniz Feneri",
      "Hastane",
      "Şizofreni",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "The Wolf Of Wall Street",
    forbiddenWords: [
      "Leonardo Dıcaprıo",
      "Martın Scorsese",
      "Banka",
      "Borsa",
      "Para",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Shınıng",
    forbiddenWords: ["Jack Nıcholson", "Stanley Kubrick", "Kar", "Otel", "Kız"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Otomatik Portakal",
    forbiddenWords: ["Stanley Kubrıck", "Kitap", "Karakter", "Kötü", "Karmaşa"],

    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Full Metal Jacket",
    forbiddenWords: ["Stanley Kubrıck", "Vıetnam", "Ordu", "Silah", "Asker"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Rezervuar Köpekleri",
    forbiddenWords: ["Quentın Tarantıno", "Kan", "Soygun", "Kaçmak", "Silah"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Galata Kulesi",
    forbiddenWords: ["İstanbul", "Kule", "Tarihi", "Manzara", "Turistik"],
    category: ["2", "4", "9", "6"],
  },
  {
    spokenWord: "Game Of Thrones",
    forbiddenWords: ["Wınter", "Jon Snow", "Dragon", "Westeros", "Hbo"],
    category: ["5", "6"],
  },
  {
    spokenWord: "Esaretin Bedeli",
    forbiddenWords: [
      "Morgan Freeman",
      "Hapishane",
      "Tım Robbıns",
      "Stephen Kıng",
      "Özgürlük",
    ],
    category: ["5", "6", "4"],
  },
  {
    spokenWord: "12 Öfkeli Adam",
    forbiddenWords: ["İkna Etmek", "Jüri", "Mahkeme", "Suçlu", "Henry Fonda"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Forrest Gump",
    forbiddenWords: ["Film", "Tom Hanks", "Koşmak", "Çikolata", "Vıetnam"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Matrıx",
    forbiddenWords: [
      "Kırmızı",
      "Keanu Reeves",
      "Neo",
      "Morpheus",
      "Sımülasyon",
    ],
    category: ["5", "6", "4"],
  },
  {
    spokenWord: "Yeşil Yol",
    forbiddenWords: [
      "Korkmak",
      "Tom Hanks",
      "Hapishane",
      "Idrıs Elba",
      "Ölüm Cezası",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Piyanist",
    forbiddenWords: [
      "Palto",
      "Müzik",
      "2. Dünya Savaşı",
      "Polonya",
      "Adrıen Brody",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Psycho",
    forbiddenWords: [
      "Katil",
      "Korku",
      "Alfred Hıtchcock",
      "Otel",
      "Norman Bates",
    ],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Gladyatör",
    forbiddenWords: ["Kılıç", "Roma", "Arena", "Russell Crowe", "Savaşçı"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Requıem For A Dream",
    forbiddenWords: ["Televizyon", "Rüya", "Jared Leto", "Bağımlılık", "Müzik"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Eternal Sunshıne Of The Spotless Mınd",
    forbiddenWords: ["Jım Carrey", "Hafıza", "Silme", "Kate Wınslet", "Aşk"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Amelıe",
    forbiddenWords: ["Fransa", "Aşk", "Kafe", "Audrey Tautou", "Masumiyet"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Scarface",
    forbiddenWords: ["Gangster", "Uzı", "Al Pacıno", "Silah", "Mıamı"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Eşkıya",
    forbiddenWords: [
      "Hapis",
      "Baran",
      "Uğur Yücel",
      "Şener Şen",
      "Yavuz Turgul",
    ],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Züğürt Ağa",
    forbiddenWords: ["Şener Şen", "Köy", "Satılık", "İstanbul", "Zengin"],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Kaybedenler Kulübü",
    forbiddenWords: [
      "Radyo",
      "Nejat İşler",
      "Yiğit Özşener",
      "İstanbul",
      "Erol Egemen",
    ],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Kabadayı",
    forbiddenWords: [
      "İntikam",
      "Kenan İmirzalıoğlu",
      "Ali Osman",
      "Mafya",
      "Ölüm",
    ],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Vizontele",
    forbiddenWords: ["Köy", "Televizyon", "Yılmaz Erdoğan", "Komedi", "Sinema"],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Gora",
    forbiddenWords: ["Cem Yılmaz", "Arog", "Komedi", "Garavel", "Arif"],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Arog",
    forbiddenWords: [
      "Cem Yılmaz",
      "Komedi",
      "Taş Devri",
      "Zaman Makinesi",
      "Gora",
    ],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Nefes Vatan Sağolsun",
    forbiddenWords: ["Asker", "Terör", "Karakol", "Komando", "Vatan"],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Pardon",
    forbiddenWords: [
      "Ceza",
      "Ferhan Şensoy",
      "Rasim Öztekin",
      "Komedi",
      "Hapishane",
    ],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Babam Ve Oğlum",
    forbiddenWords: ["İşkence", "Fikret Kuşkan", "Hastane", "Darbe", "Çocuk"],
    category: ["8", "6"],
  },
  {
    spokenWord: "Ayla",
    forbiddenWords: ["Kore", "Savaş", "Kız Çocuk", "Asker", "Dostluk"],
    category: ["4", "8", "6"],
  },
  {
    spokenWord: "Kurtlar Vadisi",
    forbiddenWords: [
      "Polat Alemdar",
      "Mafya",
      "Cerrahpaşalı Halit",
      "Necati Şaşmaz",
      "Süleyman Çakır",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Ezel",
    forbiddenWords: [
      "İntikam",
      "Kenan İmirzalıoğlu",
      "Kerpeten Ali",
      "Ömer",
      "Hapishane",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Leyla İle Mecnun",
    forbiddenWords: [
      "Hırsız Yavuz",
      "İsmail Abi",
      "İskender Abi",
      "Erdal Bakkal",
      "Ali Atay",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Behzat Ç",
    forbiddenWords: [
      "Polis",
      "Ankara",
      "Cinayet",
      "Erdal Beşikçioğlu",
      "Akbaba",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "İşler Güçler",
    forbiddenWords: [
      "Komedi",
      "Ahmet Kural",
      "Murat Cemcir",
      "Kardeş Payı",
      "Selçuk Aydemir",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Kardeş Payı",
    forbiddenWords: [
      "Tesisat",
      "Ahmet Kural",
      "Murat Cemcir",
      "Kardeş Payı",
      "Selçuk Aydemir",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Avrupa Yakası",
    forbiddenWords: [
      "Nişantaşı",
      "Burhan Altıntop",
      "Volkan",
      "Muhallebici",
      "Gülse Birsel",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Ekmek Teknesi",
    forbiddenWords: [
      "Savaş Dinçel",
      "Fırın",
      "Osman Sınav",
      "Mahalle",
      "Heredot Cevdet",
    ],
    category: ["8", "6"],
  },
  {
    spokenWord: "Duman",
    forbiddenWords: ["Grup", "Rock", "Kaan Tangöze", "Konser", "Gitar"],
    category: ["7", "6"],
  },
  {
    spokenWord: "Gripin",
    forbiddenWords: [
      "Grup",
      "Rock",
      "Durma Yağmur",
      "Aşk Nerden Nereye",
      "Yalnızlığın Çaresini Bulmuşlar",
    ],
    category: ["7", "6"],
  },
  {
    spokenWord: "Ceza",
    forbiddenWords: [
      "Neyim Var Ki",
      "Sagopa Kajmer",
      "Yerli Plaka",
      "Suspus",
      "Holocaust",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Ümit Besen",
    forbiddenWords: [
      "Slow",
      "Nikah Masası",
      "Aşk",
      "Seni Unutmaya Ömrüm Yeter Mi",
      "Dostlar Sağolsun",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Eminem",
    forbiddenWords: [
      "Amerika",
      "Slım Shady",
      "Lose Yourself",
      "Not Afraıd",
      "Rap God",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Killa Hakan",
    forbiddenWords: [
      "Almanya",
      "Fight Kulüp",
      "Her Şey Yolundadır",
      "İlk Kural Saygı",
      "Underground",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Hayko Cepkin",
    forbiddenWords: [
      "Rock",
      "Müzik",
      "Sahne",
      "Alternatif",
      "Konser",
      "Albüm",
      "Sanatçı",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Şebnem Ferah",
    forbiddenWords: [
      "Sil Baştan",
      "Yağmurlar",
      "Can Kırıkları",
      "Rock",
      "Kadın",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Müslüm Gürses",
    forbiddenWords: [
      "Arabesk",
      "Baba",
      "Nilüfer",
      "Kaç Kadeh Kırıldı",
      "Tutamıyorum Zamanı",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Mabel Matiz",
    forbiddenWords: [
      "Antidepresan",
      "Öyle Kolaysa",
      "Fırtına",
      "Ahu",
      "Sarmaşık",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Erkin Koray",
    forbiddenWords: [
      "Rock",
      "Fesuphanallah",
      "Seni Her Gördüğümde",
      "Öyle Bir Geçer Zaman Ki",
      "Anadolu Rock",
    ],
    category: ["7", "6", "1"],
  },
  {
    spokenWord: "Kanuni Sultan Süleyman",
    forbiddenWords: [
      "Padişah",
      "Osmanlı",
      "Hürrem",
      "Fatih Sultan Mehmet",
      "Pargalı",
    ],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Yavuz Sultan Selim",
    forbiddenWords: ["Padişah", "Osmanlı", "Köprü", "Halife", "Küpe"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Barbaros Hayrettin Paşa",
    forbiddenWords: [
      "Deniz",
      "Osmanlı",
      "Akdeniz",
      "Donanma",
      "Kaptan-I Derya",
    ],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Mehmet Akif Ersoy",
    forbiddenWords: ["Safahat", "İstiklal Marşı", "Şair", "Milli", "Asım"],
    category: ["9", "6", "1", "4", "3"],
  },
  {
    spokenWord: "Mimar Sinan",
    forbiddenWords: ["Osmanlı", "Selimiye", "Köprü", "Süleymaniye", "Külliye"],
    category: ["9", "6", "1", "4"],
  },
  {
    spokenWord: "İsmet İnönü",
    forbiddenWords: [
      "Atatürk",
      "Lozan",
      "İkinci Adam",
      "Milli Şef",
      "Başbakan",
    ],
    category: ["9", "6", "1"],
  },
  {
    spokenWord: "Nene Hatun",
    forbiddenWords: ["Erzurum", "Savaş", "Kadın", "Kale", "Aziziye"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Alparslan",
    forbiddenWords: ["Selçuklu", "Malazgirt", "Sultan", "Anadolu", "Savaş"],
    category: ["9", "6", "4"],
  },

  {
    spokenWord: "Karagöz Ve Hacivat",
    forbiddenWords: ["Gölge Oyunu", "Perde", "Osmanlı", "Komedi", "Diyalog"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Sahaf",
    forbiddenWords: ["Kitap", "Yazar", "Okumak", "Eski", "Satmak"],
    category: ["3", "4", "6"],
  },
  {
    spokenWord: "Araba Sevdası",
    forbiddenWords: [
      "Recaizade Mahmud Ekrem",
      "Roman",
      "Otomobil",
      "Serveti Funun",
      "Realist",
    ],
    category: ["3", "4", "6"],
  },
  {
    spokenWord: "Dede Korkut",
    forbiddenWords: ["Hikaye", "Oğuz Boyu", "Ata", "Yaşlı", "Oğul"],
    category: ["9", "6", "3", "4"],
  },
  {
    spokenWord: "Keloğlan",
    forbiddenWords: ["Hikaye", "Saç", "Erkek", "Eşek", "Ay Kız"],
    category: ["8", "6", "4", "3"],
  },
  {
    spokenWord: "Sırt Çantası",
    forbiddenWords: ["Okul", "İç", "Fermuar", "Eşya", "Takmak"],
    category: ["6"],
  },
  {
    spokenWord: "Aşkı Memnu",
    forbiddenWords: ["Beren Saat", "Bihter", "Behlül", "Firdevs Hanım", "Dizi"],
    category: ["8", "6", "4", "3"],
  },
  {
    spokenWord: "Kurtlar Vadisi",
    forbiddenWords: ["Polat Alemdar", "Memati", "Dizi", "Mafya", "Abdülhey"],
    category: ["8", "6", "4"],
  },
  {
    spokenWord: "Adını Feriha Koydum",
    forbiddenWords: [
      "Emir Sarrafoğlu",
      "Hazal Kaya",
      "Çağatay Ulusoy",
      "Asansör",
      "Bayılmak",
    ],
    category: ["8", "6", "4"],
  },
  {
    spokenWord: "Arka Sokaklar",
    forbiddenWords: [
      "Hüsnü Çoban",
      "Rıza Baba",
      "Mesut Komiser",
      "Polis",
      "Pislik",
    ],
    category: ["8", "6", "4"],
  },
  {
    spokenWord: "Kroki",
    forbiddenWords: ["Harita", "Kuşbakışı", "Ölçek", "Çizmek", "Yer"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Erozyon",
    forbiddenWords: ["Toprak", "Taşınmak", "Rüzgar", "Ağaç", "Kuraklık"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Küresel Isınma",
    forbiddenWords: [
      "Sıcaklık",
      "İklim Değişikliği",
      "Artmak",
      "Güneş",
      "Dünya",
    ],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Boylam",
    forbiddenWords: ["Meridyen", "Enlem", "Paralel", "Dünya", "Greenwich"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Barometre",
    forbiddenWords: ["Ölçmek", "Basınç", "Atmosfer", "Hava", "Toriçelli"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Peri Bacaları",
    forbiddenWords: [
      "Nevşehir",
      "Sihirli Annem",
      "Duman",
      "Ürgüp",
      "Kapadokya",
    ],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Göbekli Tepe",
    forbiddenWords: ["Şanlıurfa", "Tarihi", "Tapınak", "Karın", "Yerleşim"],
    category: ["2", "6", "4", "9"],
  },
  {
    spokenWord: "Pamukkale",
    forbiddenWords: ["Denizli", "Kaplıca", "Traverten", "Beyaz", "Turizm"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Sümela Manastırı",
    forbiddenWords: ["Trabzon", "Karadeniz", "Kilise", "Laz", "Ortodoks"],
    category: ["2", "6", "4", "9"],
  },
  {
    spokenWord: "Balıklıgöl",
    forbiddenWords: ["Şanlıurfa", "Hz. İbrahim", "Ateş", "Yüzmek", "Deniz"],
    category: ["2", "6", "4", "9"],
  },
  {
    spokenWord: "Ekinoks",
    forbiddenWords: ["Gece", "Gündüz", "Eşit", "Gün Dönümü", "Dönence"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Nil Nehri",
    forbiddenWords: ["Mısır", "Suyolu", "Uzun", "Kanal", "Irmak"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Göronland",
    forbiddenWords: ["Kuzey", "Kutup", "Buzul", "Eskimo", "Ada"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Moğolistan",
    forbiddenWords: ["Cengiz Han", "Orta Asya", "Ülke", "Çekik", "Türk"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Kızıldeniz",
    forbiddenWords: ["Mısır", "Firavun", "Musa", "Asa", "Yarmak"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Güney Kore",
    forbiddenWords: ["Seul", "Çekik", "Asya", "Noodle", "Bts"],
    category: ["2", "6", "4"],
  },
  {
    spokenWord: "Japonya",
    forbiddenWords: ["Asya", "Sushi", "Tokyo", "Tsunami", "Çekik"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Cengiz Han",
    forbiddenWords: ["Moğol", "Hükümdar", "Mete Han", "Kağan", "Savaş"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Mete Han",
    forbiddenWords: ["Teoman", "Kağan", "Onluk Sistem", "Hükümdar", "Hun"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Çanakkale Savaşı",
    forbiddenWords: [
      "18 Mart",
      "Mustafa Kemal Atatürk",
      "Anafartalar",
      "Conk Bayırı",
      "I. Dünya Savaşı",
    ],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Evliya Çelebi",
    forbiddenWords: ["Seyahatname", "Gezgin", "Osmanlı", "Yazar", "Seyyah"],
    category: ["9", "6", "4", "1"],
  },
  {
    spokenWord: "Nasreddin Hoca",
    forbiddenWords: [
      "Eşek",
      "Akşehir",
      "Maya Çalmak",
      "Fıkra",
      "Kazan Doğurdu",
    ],
    category: ["1", "6", "4", "3"],
  },
  {
    spokenWord: "Topkapı Sarayı",
    forbiddenWords: ["Osmanlı", "Padişah", "İstanbul", "Ayasofya", "Harem"],
    category: ["4", "6", "9"],
  },
  {
    spokenWord: "Sokullu Mehmet Paşa",
    forbiddenWords: [
      "Kanuni Sultan Süleyman",
      "Sadrazam",
      "Vezir",
      "Padişah",
      "Osmanlı",
    ],
    category: ["4", "6", "9"],
  },
  {
    spokenWord: "Hz. Muhammed",
    forbiddenWords: ["Peygamber", "Kuran", "İslam", "Allah", "Vahiy"],
    category: ["1", "6", "4", "9"],
  },
  {
    spokenWord: "Piri Reis",
    forbiddenWords: ["Afet", "Japonya", "Dalga", "Deniz", "Sel"],
    category: ["2", "6"],
  },
  {
    spokenWord: "Zeugma Müzesi",
    forbiddenWords: ["Gaziantep", "Çingene Kızı", "Mozaik", "Tarihi", "Antik"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Ergenekon Destanı",
    forbiddenWords: ["Kurt", "Göktürkler", "Yeniden Doğuş", "Oğuzlar", "Demir"],
    category: ["3", "6", "4", "9"],
  },
  {
    spokenWord: "Yerebatan Sarnıcı",
    forbiddenWords: ["Su", "Sütun", "Medusa", "İstanbul", "I. Justinianus"],
    category: ["9", "6", "4"],
  },
  {
    spokenWord: "Safranbolu Evleri",
    forbiddenWords: ["Karabük", "Tarihi", "Eski", "Konak", "Yerleşim"],
    category: ["4", "6", "9"],
  },
  {
    spokenWord: "Nemrut Dağı",
    forbiddenWords: ["Adıyaman", "Kommagene", "Heykel", "Unesco", "Güneydoğu"],
    category: ["2", "6", "4", "9"],
  },
  {
    spokenWord: "Anıtkabir",
    forbiddenWords: [
      "Ankara",
      "Mustafa Kemal Atatürk",
      "Mezar",
      "Anıt",
      "Müze",
    ],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Hattuşaş",
    forbiddenWords: ["Hitit", "Antik", "Arkeoloji", "Unesco", "Çorum"],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Arkeoloji",
    forbiddenWords: ["Kazı", "Yer", "Toprak", "Tarihi Eser", "Antik"],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Çin Seddi",
    forbiddenWords: ["Duvar", "Uzay", "Kale", "Çekik", "Savaş"],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Tac Mahal",
    forbiddenWords: [
      "Hindistan",
      "Amir Khan",
      "Beyaz Mermer",
      "Babür",
      "Türbe",
    ],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Kızıl Meydan",
    forbiddenWords: ["Rusya", "Kremlin", "Lenin", "Bolşevik", "Moskova"],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Pisa Kulesi",
    forbiddenWords: [
      "İtalya",
      "Eğik",
      "Fotoğraf",
      "Mucizeler Meydanı",
      "Turist",
    ],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Kolezyum",
    forbiddenWords: ["Roma", "İtalya", "Amfi Tiyatro", "Arena", "Gladyatörler"],
    category: ["6", "4", "9"],
  },
  {
    spokenWord: "Nemrut Dağı",
    forbiddenWords: ["Adıyaman", "Kommagene", "Heykel", "Unesco", "Güneydoğu"],
    category: ["2", "6", "4", "9"],
  },
  {
    spokenWord: "Yaşar Kemal",
    forbiddenWords: ["İnce Mehmet", "Çukurova", "Roman", "Kemal Tahir", "Köy"],
    category: ["1", "3", "4", "6"],
  },
  {
    spokenWord: "Servet-İ Fünun",
    forbiddenWords: [
      "Dönem",
      "Dergi",
      "Osmanlı",
      "Tevfik Fikret",
      "Halit Ziya Uşaklıgil",
    ],
    category: ["3", "4", "6", "9"],
  },
  {
    spokenWord: "Halide Edip Adıvar",
    forbiddenWords: ["Yazar", "Cumhuriyet", "Kadın", "Ateşten Gömlek", "Savaş"],
    category: ["1", "4", "6", "3"],
  },
  {
    spokenWord: "Sait Faik Abasıyanık",
    forbiddenWords: [
      "Hikaye",
      "Adalar",
      "Semaver",
      "Öykü",
      "Alemdağda Var Bir Yılan",
    ],
    category: ["1", "3", "4", "6"],
  },
  {
    spokenWord: "Ahmet Hamdi Tanpınar",
    forbiddenWords: [
      "Huzur",
      "Saatleri Ayarlama Enstitüsü",
      "Beş Şehir",
      "Mahur Beste",
      "Yahya Kemal Beyatlı",
    ],
    category: ["1", "3", "4", "6"],
  },
  {
    spokenWord: "Helikopter",
    forbiddenWords: ["Pervane", "Sürmek", "Hava", "Taşıt", "Uçmak"],
    category: ["6"],
  },
  {
    spokenWord: "Televizyon Koltuğu",
    forbiddenWords: ["Kanepe", "Sandalye", "Yatmak", "Uzanmak", "Rahat"],
    category: ["6"],
  },
  {
    spokenWord: "Bardak Tutucu",
    forbiddenWords: ["Karton", "İçmek", "Araba", "Dökmek", "İçecek"],
    category: ["6"],
  },
  {
    spokenWord: "Öğleden Sonra",
    forbiddenWords: ["Önce", "Gündüz", "Sabah", "İkindi", "Gece"],
    category: ["6"],
  },
  {
    spokenWord: "Göl",
    forbiddenWords: ["Su", "Okyanus", "Deniz", "Küçük", "Van"],
    category: ["6"],
  },
  {
    spokenWord: "Koşmak",
    forbiddenWords: ["Depar", "Yürümek", "Hızlı", "Maraton", "Hareket"],
    category: ["6"],
  },
  {
    spokenWord: "Nemlendirici",
    forbiddenWords: ["Cilt", "Yumuşak", "Krem", "Losyon", "Kozmetik"],
    category: ["6"],
  },
  {
    spokenWord: "Akne",
    forbiddenWords: ["Siyah Nokta", "Ergen", "Sivilce", "Yüz", "Cildiye"],
    category: ["6"],
  },
  {
    spokenWord: "Pozitif",
    forbiddenWords: ["Negatif", "Olumlu", "İyi", "Kesin", "Bilim"],
    category: ["6"],
  },
  {
    spokenWord: "Kırışıklık",
    forbiddenWords: ["Çamaşır", "Çizgi", "Yaşlanmak", "Cilt", "Yüz"],
    category: ["6"],
  },
  {
    spokenWord: "Neon",
    forbiddenWords: ["Işık", "Parlak", "Tabela", "Renk", "Gaz"],
    category: ["6"],
  },
  {
    spokenWord: "Elma",
    forbiddenWords: ["Yeşil", "Kırmızı", "Turta", "Meyve", "Sirke"],
    category: ["6"],
  },
  {
    spokenWord: "Krem Peynir",
    forbiddenWords: ["Sürmek", "Ekmek", "Kahvaltı", "Yumuşak", "Eritme"],
    category: ["6"],
  },
  {
    spokenWord: "Termometre",
    forbiddenWords: ["Ateş", "Derece", "Sıcak", "Bebek", "Hastalık"],
    category: ["6"],
  },
  {
    spokenWord: "Deniz Feneri",
    forbiddenWords: ["Bina", "Uyarı", "Sahil", "Gemi", "Sis"],
    category: ["6"],
  },
  {
    spokenWord: "Hazine",
    forbiddenWords: ["Gömmek", "Ada", "Altın", "Sandık", "Korsan"],
    category: ["6"],
  },
  {
    spokenWord: "Örümcek",
    forbiddenWords: ["Sekiz", "Bacak", "Böcek", "Karadul", "Ağ"],
    category: ["6"],
  },
  {
    spokenWord: "Bahşiş",
    forbiddenWords: ["Cömert", "Restoran", "Yiyecek", "Hesap", "Para"],
    category: ["6"],
  },
  {
    spokenWord: "Ders",
    forbiddenWords: ["Okul", "Anlatmak", "Eğitim", "Sınav", "Öğrenmek"],
    category: ["6"],
  },
  {
    spokenWord: "Hamster",
    forbiddenWords: ["Hayvan", "Kemirgen", "Kafes", "Fare", "Çark"],
    category: ["6"],
  },
  {
    spokenWord: "Spor Ayakkabı",
    forbiddenWords: ["Giymek", "Koşmak", "Bağcık", "Rahat", "Konforlu"],
    category: ["6"],
  },
  {
    spokenWord: "Antik",
    forbiddenWords: ["Eski", "Tarih", "Geçmiş", "Zaman", "Roma"],
    category: ["6"],
  },
  {
    spokenWord: "Taklit",
    forbiddenWords: ["Sahte", "Hile", "Gerçek", "Kandırmaca", "Benzer"],
    category: ["6"],
  },
  {
    spokenWord: "Garson",
    forbiddenWords: ["Restoran", "Sipariş", "Servis", "Bahşiş", "Yemek"],
    category: ["6"],
  },
  {
    spokenWord: "Deşifre Etmek",
    forbiddenWords: ["Kod", "Yorumlamak", "Gizem", "Okumak", "Çözmek"],
    category: ["6"],
  },
  {
    spokenWord: "Sim",
    forbiddenWords: ["Parlak", "Renkli", "Süsleme", "Tutkal", "Okul"],
    category: ["6"],
  },
  {
    spokenWord: "Batman",
    forbiddenWords: ["Şehir", "Gotham", "Süper Kahraman", "Pelerin", "Joker"],
    category: ["4", "5", "6"],
  },
  {
    spokenWord: "Dede",
    forbiddenWords: ["Yaşlı", "Baba", "Peder", "Erkek", "İhtiyar"],
    category: ["6"],
  },
  {
    spokenWord: "Puantiye",
    forbiddenWords: ["Nokta", "Daire", "Kumaş", "Yuvarlak", "Desen"],
    category: ["6"],
  },
  {
    spokenWord: "Gardırop",
    forbiddenWords: ["Giysi", "Kostüm", "Sahne", "Dolap", "Kıyafet"],
    category: ["6"],
  },
  {
    spokenWord: "Köpük",
    forbiddenWords: ["Sabun", "Bira", "Yıkamak", "Banyo", "Hacı Şakir"],
    category: ["6"],
  },
  {
    spokenWord: "Çizgi",
    forbiddenWords: ["Yatay", "Dikey", "Doğrusal", "Düz", "Yamuk"],
    category: ["6"],
  },
  {
    spokenWord: "Kahve",
    forbiddenWords: ["İçmek", "Sabah", "Kafein", "Sade", "Sıcak"],
    category: ["6"],
  },
  {
    spokenWord: "Talih Kuşu",
    forbiddenWords: ["Para", "Beklenmedik", "İyi", "Hediye", "Servet"],
    category: ["6"],
  },
  {
    spokenWord: "Kapuçino",
    forbiddenWords: ["Kahve", "Süt", "İçmek", "Sıcak", "Köpük"],
    category: ["6"],
  },
  {
    spokenWord: "Kum",
    forbiddenWords: ["Sahra", "Plaj", "Çöl", "Deniz", "Sahil"],
    category: ["6"],
  },
  {
    spokenWord: "Garaj",
    forbiddenWords: ["Araba", "Park", "Ev", "Paralı", "Kapı"],
    category: ["6"],
  },
  {
    spokenWord: "Zeki",
    forbiddenWords: ["Aptal", "Akıllı", "Eğitim", "Parlak", "Salak"],
    category: ["6"],
  },
  {
    spokenWord: "Onur Belgesi",
    forbiddenWords: ["Okul", "Not", "Yüksek", "Ortalama", "Üniversite"],
    category: ["6"],
  },
  {
    spokenWord: "Patlamak",
    forbiddenWords: [
      "Yanmak",
      "İnfilak Etmek",
      "Püskürmek",
      "Dinamit",
      "Bomba",
    ],
    category: ["6"],
  },
  {
    spokenWord: "Çedar",
    forbiddenWords: ["Peynir", "Eski", "Taze", "Mandıra", "Hamburger"],
    category: ["6"],
  },
  {
    spokenWord: "Muz",
    forbiddenWords: ["Meyve", "Sarı", "Soymak", "Maymun", "Uzun"],
    category: ["6"],
  },
  {
    spokenWord: "Çam Ağacı",
    forbiddenWords: ["Bal", "Kozalak", "Orman", "Sivri", "İğne"],
    category: ["6"],
  },
  {
    spokenWord: "Tartı",
    forbiddenWords: ["Pazar", "Ağırlık", "Diyet", "Çıkmak", "Kilogram"],
    category: ["6"],
  },
  {
    spokenWord: "Üst Kat",
    forbiddenWords: ["Merdiven", "Zemin", "Bodrum", "Ev", "Oda"],
    category: ["6"],
  },
  {
    spokenWord: "Havaalanı",
    forbiddenWords: ["Gezmek", "Uçak", "Güvenlik", "Kalkmak", "Apron"],
    category: ["6"],
  },
  {
    spokenWord: "Tazelenmek",
    forbiddenWords: [
      "Ferahlanmak",
      "Yenilenmek",
      "Canlanmak",
      "Temizlik",
      "Arınmak",
    ],
    category: ["6"],
  },
  {
    spokenWord: "Anahtar",
    forbiddenWords: ["Ev", "Araba", "Kalp", "Kaybolmak", "Kapı"],
    category: ["6"],
  },
  {
    spokenWord: "Anneanne",
    forbiddenWords: ["Yaşlı", "Nine", "Soy", "Akraba", "Baba"],
    category: ["6"],
  },
  {
    spokenWord: "Tatlı",
    forbiddenWords: ["Şekerli", "Baklava", "Kriz", "Ekşi", "Çikolata"],
    category: ["6"],
  },
  {
    spokenWord: "Dilimlemek",
    forbiddenWords: ["Kesmek", "Sebze", "Et", "Bıçak", "Ekmek"],
    category: ["6"],
  },
  {
    spokenWord: "Vale",
    forbiddenWords: ["Park", "Sürmek", "Bahşiş", "Araba", "Restoran"],
    category: ["6"],
  },
  {
    spokenWord: "Şık",
    forbiddenWords: ["Smokin", "Düğün", "Nikah", "Giyim", "Etkinlik"],
    category: ["6"],
  },
  {
    spokenWord: "Biber",
    forbiddenWords: ["Acı", "Sivri", "Kırmızı", "Kara", "Tuz"],
    category: ["6"],
  },
  {
    spokenWord: "Teyze",
    forbiddenWords: ["Yeğen", "Kuzen", "Kardeş", "Anne", "Akraba"],
    category: ["6"],
  },
  {
    spokenWord: "Soymak",
    forbiddenWords: ["Muz", "Meyve", "Deri", "Kabuk", "Bıçak"],
    category: ["6"],
  },
  {
    spokenWord: "Yavaş",
    forbiddenWords: ["Sakin", "Hızlı", "Hareket", "Yürümek", "Mansur"],
    category: ["6"],
  },
  {
    spokenWord: "Kirli Sakal",
    forbiddenWords: ["Tıraş", "Erkek", "Günlük", "Uzamak", "Saç"],
    category: ["6"],
  },
  {
    spokenWord: "Dolma Kalem",
    forbiddenWords: ["Yazı", "Tükenmez", "Keçeli", "Kurşun", "Mürekkep"],
    category: ["6"],
  },
  {
    spokenWord: "Piknik",
    forbiddenWords: ["Sepet", "Yemek", "Dışarı", "Çıkmak", "Mangal"],
    category: ["6"],
  },
  {
    spokenWord: "Hoş Geldin",
    forbiddenWords: ["Ev Sahibi", "Misafir", "Karşılamak", "Sıcak", "Kapı"],
    category: ["6"],
  },
  {
    spokenWord: "Düğüm",
    forbiddenWords: ["Bağlamak", "İplik", "İlmek", "Balıkçı", "Dolanmak"],
    category: ["6"],
  },
  {
    spokenWord: "Şeftali",
    forbiddenWords: ["Yumuşak", "Sulu", "Meyve", "Kayısı", "Çekirdek"],
    category: ["6"],
  },
  {
    spokenWord: "Broadway",
    forbiddenWords: ["New York", "Sahne", "Gösteri", "Tiyatro", "Yıldız"],
    category: ["6"],
  },
  {
    spokenWord: "Venüs",
    forbiddenWords: ["Dünya", "Tanrıça", "Gezegen", "Uzay", "Güzellik"],
    category: ["6"],
  },
  {
    spokenWord: "Kül",
    forbiddenWords: ["Yakmak", "Şömine", "Odun", "Toz", "Sigara"],
    category: ["6"],
  },
];
export default Word;
